In [1]:
import pandas as pd 
import numpy as np 
import re

/var/folders/wc/dg5vr0h57jvg48dksgcxz02w0000gn/T/ipykernel_66318/3859853065.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv("/Users/siddhant/housepriceproject/Capstone/data/raw/flats.csv")
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [3]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                 1
area                 12
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom     1314
address               6
floorNum              2
facing              881
agePossession         1
nearbyLocations      95
description           0
furnishDetails      805
features            414
rating              332
property_id           0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3008 entries, 0 to 3007
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3008 non-null   object
 1   link             3008 non-null   object
 2   society          3007 non-null   object
 3   price            3007 non-null   object
 4   area             2996 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 470.1+ KB

In [5]:
df.duplicated().sum()

0

In [6]:
# DROPPING UNNECESSARY COLUMNS
print(f"Shape of dataframe before dropping columns {df.shape}")

df.drop(columns=["link", "description", "property_id"], inplace=True)

print(f"Shape of dataframe after dropping columns {df.shape}")

Shape of dataframe before dropping columns (3008, 20)
Shape of dataframe after dropping columns (3008, 17)

In [7]:
# CONVERTING PRICE COLUMN INTO ONE SINGLE UNIT (CRORES)
df["price"].value_counts()

price
1.25 Crore     79
1.1 Crore      61
1.4 Crore      60
1.5 Crore      59
1.2 Crore      59
               ..
35.5 Lac        1
4.94 Crore      1
10.75 Crore     1
9.14 Crore      1
62.5 Lac        1
Name: count, Length: 439, dtype: int64

We are not concerned with price on request value as it wont be helpful for our regression model. So we need to remove that entry from the price column.

In [8]:
df = df[df["price"] != "Price on Request"]

def price(value):
    if type(value) == float:
        return value
    else:
        if value[1] == "Lac":
            return round(float(value[0])/100, 2)
        else:
            return round(float(value[0]),2)
   
    

df["price"] =  df["price"].str.split(" ").apply(price)
df.sample(5)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,rating
1517,3 BHK Flat in Sector 109 Gurgaon,ATS Tourmaline3.9 ★,1.5,"₹ 6,976/sq.ft.",Super Built up area 2150(199.74 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"F Floor, Sector 109 Gurgaon, Gurgaon, Haryana",4th of 27 Floors,North-West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'NeoSquare ...","['5 Fan', '1 Exhaust Fan', '10 Light', '4 Ward...","['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
1553,3 BHK Flat in Sector 81 Gurgaon,DLF The Ultima4.0 ★,2.3,"₹ 14,603/sq.ft.",Super Built up area 2100(195.1 sq.m.)Carpet ar...,3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"1408, Sector 81 Gurgaon, Gurgaon, Haryana",27th of 29 Floors,East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Vatika Town...","['3 Wardrobe', '1 Exhaust Fan', '3 Geyser', '4...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area5 out of 5', 'Construction4 out of..."
2930,2 BHK Flat in Sector 95 Gurgaon,Sidhartha NCR Greens4.3 ★,0.6,"₹ 5,576/sq.ft.",Super Built up area 1076(99.96 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 95 Gurgaon, Gurgaon, Haryana",14th of 21 Floors,NaN,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",NaN,"['Lift(s)', 'Park', 'Piped-gas', 'Security Per...","['Management4 out of 5', 'Green Area5 out of 5..."
1005,2 BHK Flat in Sector 88A Gurgaon,Godrej Oasis3.9 ★,1.0,"₹ 6,896/sq.ft.",Carpet area: 1450 (134.71 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 88A Gurgaon, Gurgaon, Haryana",7th of 17 Floors,NaN,1 to 5 Year Old,"['Double Infinity market', 'Pataudi road', 'Dw...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4.5 out ..."
2780,2 BHK Flat in Sector 68 Gurgaon,Pareena Mi Casa,1.1,"₹ 8,835/sq.ft.",Super Built up area 1245(115.66 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sector 68 Gurgaon, Gurgaon, Haryana",11st of 25 Floors,North,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Airia Mall', '...",NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Safety5 out of 5', 'Lifestyle4 out of 5', 'E..."

In [9]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df["society"].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Emaar MGF Emerald Floors Premier3.8 ★                32
Smart World Orchard                                  32
Smart World Gems                                     32
DLF The Ultima4.0 ★                                  31
Paras Dews                                           31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
La Vida by Tata Housing                              28
Signature Global Solera3.7 ★                         27
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
Experion The Heartsong3.9 ★                          24
DLF New Town Heights 13.9 ★                          24
Eldeco Accolade3.8 ★                                 24
Vatika Gurgaon 213.7 ★                               24
Bestech Park View Residency3.9 ★                     23
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
M3M Heights                                          22
ATS Triumph3.9 ★                                     22
Sare Crescent Parc3.5 ★                              21
ROF Ananda                                           21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Sare Homes                                           19
Antriksh Heights3.7 ★                                19
Indiabulls Centrum Park3.7 ★                         18
Ambience Creacions                                   18
CHD Avenue 713.6 ★                                   18
ATS Tourmaline3.9 ★                                  18
Sobha City                                           18
Mapsko Mount Ville4.1 ★                              18
M3M Skywalk                                          17
Supertech Araville                                   17
Conscient Heritage Max4.3 ★                          17
GLS Arawali Homes3.8 ★                               17
M3M Golfestate4.4 ★                                  17
Godrej Summit3.7 ★                                   16
Bestech Park View Grand Spa4.3 ★                     16
M3M Merlin3.7 ★                                      16
HCBS Sports Ville3.6 ★                               16
Pareena Coban Residences                             16
Emaar MGF The Palm Drive4.1 ★                        15
Godrej Oasis3.9 ★                                    15
Ansal Heights 86                                     15
Umang Monsoon Breeze                                 15
MVN Athens3.7 ★                                      14
Indiabulls Enigma                                    14
Imperia The Esfera                                   14
Corona Optus3.9 ★                                    14
Ireo Victory Valley4.1 ★                             14
Vatika The Seven Lamps3.8 ★                          14
Ireo Skyon4.0 ★                                      14
The Close North4.0 ★                                 14
Orchid Petals4.1 ★                                   14
Umang Winter Hills3.9 ★                              14
DLF The Primus3.9 ★                                  14
Ramsons Kshitij3.7 ★                                 14
Central Park Flower Valley                           13
Ireo The Corridors                                   13
Puri Emerald Bay3.7 ★                                13
Bestech Park View Ananda4.2 ★                        13
Adani M2K Oyster Grande3.9 ★                         11
SBTL Caladium                                        11
Alpha Corp GurgaonOne 844.0 ★                        11
Godrej Aria3.8 ★                                     11
DLF The Skycourt4.2 ★                                11
TARC Maceo3.8 ★                                      11
M3M Soulitude                                        11
Raheja Vedaanta3.6 ★                                 11
Pivotal Devaan                                       10
Puri Diplomatic Greens4.0 ★                          10
Capital Residences 360                               10
Breez Global Heights4.2 ★                            10
Godrej Air                                           10
Zara Aavaas                                          10
Ramprastha The Edge Towers3.5 ★                      10
Signature Global Synera3.4 ★                         10
Pyramid Urban Homes 2                                10
Emaar MGF Palm Hills4.0 ★                            10
Breez Global Hill View                               10
ATS Kocoon                                           10
DLF New Town Heights 24.0 ★                          10
Bestech Park View Sanskruti4.2 ★                      9
ILD Greens4.1 ★                                       9
Microtek Greenburg3.8 ★                               9
Pareena Mi Casa                                       9
Vatika City4.1 ★                                      9
Parsvnath Green Ville3.9 ★                            9
AIPL The Peaceful Homes3.9 ★                          9
Orris Aster Court Premier                             8
Bestech Altura                                        8
Tulip Ivory3.5 ★                                      8
Vatika Lifestyle Homes3.8 ★                           8
ss                                                    8
Birla Navya                                           8
AVL 36 Gurgaon3.7 ★                                   8
M3M Capital                                           8
M3M Skycity                                           8
The Lions CGHS                                        8
GLS Avenue 51                                         8
Emaar Digihomes                                       8
Sare Green ParC Phase 3                               7
Signature Andour Heights3.8 ★                         7
Emaar Imperial Gardens3.8 ★                           7
Sare Crescent Parc Royal Greens Phase 1               7
Assotech Blith                                        7
Orris Carnation Residency3.7 ★                        7
Ireo The Grand Arch4.0 ★                              7
Signature Global Orchard Avenue3.6 ★                  7
AIPL Zen Residences                                   7
Mapsko Casa Bella3.8 ★                                7
Vipul Lavanya3.9 ★                                    7
Ansal Housing Highland Park                           7
Signature Global City                                 7
Trisara Our Homes 3                                   7
BPTP Astaire Gardens3.7 ★                             6
Signature Global Park 4                               6
Suncity Vatsal Valley                                 6
M3M Sierra 68                                         6
Bestech Park View City4.1 ★                           6
HSIIDC Sidco Aravali                                  6
Supertech Hues                                        6
Pyramid Urban                                         6
Sidhartha NCR One Phase 14.2 ★                        6
Ashiana Mulberry                                      6
Pioneer Araya3.8 ★                                    6
DLF Regency Park 13.6 ★                               6
Hero Homes                                            6
Mapsko Royale Ville3.7 ★                              6
Shapoorji Pallonji Joyville Gurugram                  6
Kiran Residency                                       6
Parsvnath Exotica3.7 ★                                6
Bestech Park View Spa Next4.0 ★                       6
Signature The Roselia3.6 ★                            6
Signature Global City 63A                             6
Vatika City Homes3.9 ★                                5
Conscient Elevate                                     5
Signature Global Grand IVA3.9 ★                       5
ATS Marigold                                          5
Central Park Flower Valley Aqua Front Towers          5
Vatika Sovereign Park                                 5
Signature Global City 37D Ph 2                        5
M3M The Marina4.0 ★                                   5
Adani Brahma Samsara Vilasa                           5
Satya The Hermitage3.5 ★                              5
DLF Park Place4.1 ★                                   5
Pareena Laxmi Apartments3.6 ★                         5
Signature Global the Millennia                        5
Central Park Resorts4.4 ★                             5
Pioneer Park3.8 ★                                     5
Signature Global City 92                              5
Ashiana Anmol3.5 ★                                    5
Apna Enclave                                          5
Essel Towers                                          5
Green Court3.7 ★                                      5
Krisumi Waterfall Residences                          5
Signature Global City 81                              5
Emaar MGF Emerald Estate3.8 ★                         5
Ireo Uptown4.1 ★                                      5
DLF Regency Park 24.0 ★                               5
Greenopolis                                           5
Silverglades The Melia                                5
Godrej Habitat                                        5
Orris Aster Court                                     4
Sare Petioles                                         4
Unitech Fresco3.8 ★                                   4
Prime Habitat                                         4
ILD Grand                                             4
Corona Gracieux                                       4
Godrej Icon                                           4
Unitech Vistas                                        4
SS The Coralwood3.4 ★                                 4
DLF The Skycourt                                      4
Emaar Palm Heights                                    4
Railway Officers RPF Society                          4
Tata Gurgaon Gateway3.8 ★                             4
Global Hill View                                      4
Raheja Navodaya3.6 ★                                  4
Ramprastha Primera                                    4
Ramprastha Skyz                                       4
DLF New Town Heights3.7 ★                             4
Lotus Homz4.0 ★                                       4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Tulip Monsella                                        4
Godrej Frontier3.7 ★                                  4
Signature The Serenas                                 4
Tulip Petals3.6 ★                                     3
Raheja Revanta                                        3
Kendriya Vihar4.1 ★                                   3
DLF Express Greens3.9 ★                               3
Deepak Minda                                          3
Tulip Purple                                          3
Sare Green Parc 2                                     3
Maxworth City Residences                              3
Krrish Florence Estate                                3
Puri Diplomatic Greens3.9 ★                           3
Raheja Atharva3.6 ★                                   3
Unitech The Residences3.7 ★                           3
Unitech Uniworld Gardens3.8 ★                         3
Essel Tower                                           3
Piedmont Taksila heights3.6 ★                         3
Siddhartha Apartment                                  3
Tulip White3.5 ★                                      3
Vatika Independent Floors3.8 ★                        3
Valley View Estate                                    3
Shree Arihant Apartment                               3
Bestech Park View City 23.9 ★                         3
AFNHB Jalvayu Vihar3.7 ★                              3
Pyramid Elite                                         3
Shri Banke Bihari Society3.8 ★                        3
Brisk Lumbini Terrace Homes                           3
Krrish Provence Estate                                3
Mahindra Aura4.2 ★                                    3
Pivotal Riddhi Siddhi                                 3
Guru Gram Haryana CGHS4.1 ★                           3
Spaze Privvy The Address3.9 ★                         3
Signature Global Solera 2                             3
Whiteland Blissville                                  3
Shri Ram Apartments                                   3
Sidhartha NCR Greens4.3 ★                             3
Vatika Xpressions                                     3
DLF Royalton Tower                                    3
Ambience Lagoon3.9 ★                                  3
Sidhartha NCR One                                     3
Sare Green Parc                                       3
Unitech Sunbreeze                                     3
Smriti Apartment                                      3
Satya Element One                                     3
Paras Quartier                                        3
Chintels Paradiso3.9 ★                                3
AIPL Club Residences                                  3
Adani Aangan Arcade                                   3
ATS Kocoon4.2 ★                                       3
Suncity Platinum Towers                               3
Dhoot Time Residency4.0 ★                             3
Spaze Privy AT43.9 ★                                  3
Conscient Habitat3.6 ★                                3
DLF Carlton Estate4.0 ★                               3
Tulip Lemon3.9 ★                                      3
Spaze Privy3.9 ★                                      3
DLF Belvedere Towers3.8 ★                             3
Sunischit Apartments                                  3
SS Almeria                                            3
Raheja Sampada                                        3
Sukhshanti Apartment                                  3
Apex Our Homes                                        3
Sapphire Eighty Three                                 3
DLF The Arbour                                        3
Unitech Heritage City                                 3
DLF The Grove                                         3
Godrej Nature Plus Serenity                           2
AWHO Shanti Vihar4.0 ★                                2
Ansal API Esencia3.7 ★                                2
NBCC Heights3.9 ★                                     2
Tulip Orange3.9 ★                                     2
Mittal Surya Vihar                                    2
Suncity Avenue 76                                     2
Central Park 2 Bellevue                               2
Paras Irene3.7 ★                                      2
Suposhaa Smartworld Orchard                           2
Supertech Hill Town                                   2
Ashiana Anmol                                         2
Residency Grand                                       2
DLF The Crest3.6 ★                                    2
Sahara Grace                                          2
ROF Aalayas3.8 ★                                      2
Vatika Emilia Floors3.7 ★                             2
Vipul Belmonte3.9 ★                                   2
Bestech Park View Sanskruti4.1 ★                      2
M3M Ikonic                                            2
The Penthouses at the Hibiscus                        2
Emaar MGF The Enclave                                 2
BPTP Mansions Park Prime                              2
Housing Board Colony                                  2
om appartments                                        2
Tulip Leaf                                            2
BPTP Amstoria3.8 ★                                    2
Tulip Violet                                          2
Suncity Avenue 1023.9 ★                               2
Adani Aangan Galleria                                 2
Emaar MGF Palm Studios                                2
Professors Enclave CGHS                               2
DLF The Icon3.7 ★                                     2
Samaspurkunj                                          2
Aqua Front Towers                                     2
Orchid Island4.2 ★                                    2
Signature Global The Millennia 3                      2
DLF The Belaire3.9 ★                                  2
M3M Sky Lofts                                         2
HCBS Sports Ville                                     2
Ganga Apartment                                       2
Viridian The Plaza 106                                2
Oriental Valley CHS                                   2
Green Campus CHS                                      2
Ramprastha The Atrium3.4 ★                            2
Vasant Appartments                                    2
Maruti Vihar                                          2
Surendra Avenue 69                                    2
Unitech Uniworld Gardens 23.4 ★                       2
BPTP Pedestal                                         2
Ambience Caitriona                                    2
MRG World Ultimus                                     2
Mapsko Paradise3.9 ★                                  2
Bhagwati Sadan                                        2
Sidhivinayak Apartments                               2
Today Callidora                                       2
Suncity Heights3.7 ★                                  2
Silverglades Hightown Residences                      2
BPTP Freedom Park Life4.0 ★                           2
Jammu and Kashmir Bank Employees CGHS3.7 ★            2
Ansal Heights3.2 ★                                    2
Puri The Aravallis                                    2
My Home                                               2
M3M Urbana                                            2
Ramprastha City                                       2
Palam Vihar Society                                   2
Vatika INXT Floors                                    2
Raheja Vanya                                          2
Ardee City3.8 ★                                       2
Landmark The Residency                                2
Park Royal Apartment                                  2
M3M Latitude                                          2
Mahindra Luminare4.0 ★                                2
Elan The Presidential                                 2
Milan CGHS 9                                          2
lagoon apartment                                      2
Element One Service                                   2
Lavanya Apartments                                    2
Vipul World Floors                                    2
The Close South3.9 ★                                  2
Tulsiani Easy in Homes                                2
Bestech Spa Signature                                 2
Breeze Global Heights                                 2
Pioneer Urban Presidia                                2
Apartment                                             2
Ansal API Celebrity Suites                            2
Shapoorji Pallonji Joyville                           2
Dlf City                                              2
CGHS Airport Apartment                                2
Belgravia Resort Residences                           1
shree balaji appartment                               1
Antriksh Green                                        1
ILD Greens                                            1
Whiteland The Aspen                                   1
Mittal Cosmos Executive Apartments3.8 ★               1
Ansal Harmony Homes3.7 ★                              1
Ansal Height 86                                       1
Ramsons Kshitij                                       1

Majority of the society names have a rating and a star attached to them. We need to clean this column by removing this rating and converting all names to lower case to bring the in a standard format.

In [10]:
# CLEANING UP THE 'SOCIETY' COLUMN
def regex(value):
    cleaned_value = re.sub(r'\d+(\.\d+)?\s?★', "", str(value))
    cleaned_value = cleaned_value.lower().strip()
    return cleaned_value

df["society"] = df["society"] .apply(regex)
df.sample(5)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,rating
17,2 BHK Flat in Sector 102 Gurgaon,shapoorji pallonji joyville gurugram,1.05,"₹ 11,475/sq.ft.",Carpet area: 915 (85.01 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"G04, Sector 102 Gurgaon, Gurgaon, Haryana",Ground of 14 Floors,NaN,Mar-24,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",[],"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Amenities5 out of 5'..."
2739,1 BHK Flat in Sector 56 Gurgaon,sobha smriti apartments,0.50,"₹ 8,333/sq.ft.",Carpet area: 600 (55.74 sq.m.),1 Bedroom,1 Bathroom,2 Balconies,NaN,"Sector 56, Sector 56 Gurgaon, Gurgaon, Haryana",3rd of 3 Floors,NaN,undefined,"['Sector 54 chowk metro station', 'Sector metr...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Safety4 out of 5', 'Lifestyle5 out of 5', 'E..."
1920,1 BHK Flat in Sector 52 Gurgaon,ansal api sushant estate,0.29,"₹ 11,600/sq.ft.",Carpet area: 250 (23.23 sq.m.),1 Bedroom,1 Bathroom,No Balcony,NaN,"Sector 52 Gurgaon, Gurgaon, Haryana",Ground of 4 Floors,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Hanuman Mandir'...","['1 Fan', '1 Fridge', '1 Exhaust Fan', '1 Geys...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
725,2 BHK Flat in Sector 107 Gurgaon,m3m woodshire,0.80,"₹ 5,856/sq.ft.",Super Built up area 1366(126.91 sq.m.),2 Bedrooms,2 Bathrooms,3+ Balconies,NaN,"Sector 107 Gurgaon, Gurgaon, Haryana",7th of 14 Floors,North-East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...","['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '5 Li...","['Water purifier', 'Security / Fire Alarm', 'F...","['Green Area4.5 out of 5', 'Construction5 out ..."
2598,2 BHK Flat in Sector 92 Gurgaon,sare crescent parc,0.49,"₹ 4,909/sq.ft.",Carpet area: 998 (92.72 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 92 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4 out of 5', 'Amenities3 out of 5'..."

In [11]:
# CLEANING UP AREA COLUMN - RENAMING THE COLUMN
df.rename(columns={"area":"price_per_sqft"}, inplace=True)

In [12]:
# CLEANING UP AREA COLUMN - JUST KEEPING THE VALUE
df["price_per_sqft"] = df["price_per_sqft"].str.split("/").str.get(0).str.replace("₹", "").str.replace(",","").str.strip().astype(float)
df.sample(5)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,rating
2361,4 BHK Flat in Sector 63 Gurgaon,dlf the arbour,7.90,20000.0,Built Up area: 3950 (366.97 sq.m.)Carpet area:...,4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"A341, Sector 63 Gurgaon, Gurgaon, Haryana",34th of 42 Floors,NaN,Jan-28,"['Radhakrishna Shani Mandir', 'pracksht hospit...",[],NaN,NaN
2824,2 BHK Flat in Sector 102 Gurgaon,shapoorji pallonji joyville gurugram,1.35,14754.0,Super Built up area 915(85.01 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 102 Gurgaon, Gurgaon, Haryana",10th of 14 Floors,NaN,Sep-23,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...","['3 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Intercom Facility', 'Lift(s)', 'Park', 'Visi...","['Management4 out of 5', 'Green Area4 out of 5..."
2077,1 BHK Flat in Sector 106 Gurgaon,viridian the plaza 106,0.46,6571.0,Carpet area: 700 (65.03 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,NaN,"Sector 106 Gurgaon, Gurgaon, Haryana",18th of 26 Floors,NaN,0 to 1 Year Old,"['MG Road Metro Station', 'Dwarka Expressway',...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1665,3 BHK Flat in Sector 104 Gurgaon,ats triumph,1.85,8078.0,Super Built up area 2290(212.75 sq.m.),3 Bedrooms,4 Bathrooms,3+ Balconies,"Servant Room,Study Room,Pooja Room,Store Room","1245, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 27 Floors,East,1 to 5 Year Old,"['IFFCO Chowk Metro Station', 'The Esplanade M...","['7 Fan', '7 Light', '1 Modular Kitchen', 'No ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction5 out of..."
39,2 BHK Flat in Sector 37C Gurgaon,ild greens,0.78,5714.0,Super Built up area 1365(126.81 sq.m.)Built Up...,2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"101, Tower-7, Sector 37C Gurgaon, Gurgaon, Har...",1st of 19 Floors,North,5 to 10 Year Old,"['The Esplanade Mall', 'Gurgaon Road', 'Delhi ...","['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Amenities4.5 out of ..."

In [13]:
# NOW SINCE WE HAVE price_per_sqft AND price WE CAN ACTUALLY CREATE A FETAURE CALLED AREA.
df.insert(loc=4, column="area", value=round((df["price"] * 10000000)/df["price_per_sqft"],2))
df.insert(loc=2, column="property_type", value="flat")

df.head(5)

,property_name,society,property_type,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,flat,0.45,5000.0,900.00,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...","['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,flat,0.50,7692.0,650.03,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,flat,0.40,6722.0,595.06,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,flat,1.47,12250.0,1200.00,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,flat,0.70,5204.0,1345.12,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [14]:
# CLEANING THE BEDROOM COLUMN
print(f"{df['bedRoom'].value_counts()}")
print(f"Number of missing values in bedroom column are: {df['bedRoom'].isnull().sum()}")

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64
Number of missing values in bedroom column are: 0

No Missing values in the bedroom column. We can go ahead and clean it

In [15]:
df["bedRoom"] = df["bedRoom"].str.split(" ").str.get(0).str.strip().astype(int)
df.sample(3)

,property_name,society,property_type,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,rating
576,2 BHK Flat in Sector 107 Gurgaon,signature global solera,flat,0.27,5521.0,489.04,Carpet area: 489 (45.43 sq.m.),2,2 Bathrooms,2 Balconies,NaN,"Sector 107 Gurgaon, Gurgaon, Haryana",Ground of 14 Floors,North-East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'Dwarka Expressway', ""...",NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
2796,4 BHK Flat in Sector 92 Gurgaon,sare homes,flat,0.95,4871.0,1950.32,Super Built up area 1950(181.16 sq.m.),4,3 Bathrooms,3 Balconies,NaN,"Sector 92 Gurgaon, Gurgaon, Haryana",13rd of 25 Floors,NaN,0 to 1 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",[],NaN,"['Safety3 out of 5', 'Lifestyle4 out of 5', 'E..."
80,3 BHK Flat in Sector 30 Gurgaon,afnhb jalvayu vihar,flat,1.45,11153.0,1300.10,Built Up area: 1300 (120.77 sq.m.)Carpet area:...,3,2 Bathrooms,2 Balconies,NaN,"Sector 30 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,North,10+ Year Old,"['Icici bank ATM', 'Hdfc ATM', 'Axis bank ATM'...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area4.5 out of 5', 'Amenities4 out of ..."

In [16]:
# CLEANING THE BATHROOM COLUMN
print(f"{df['bathroom'].value_counts()}")
print(f"Number of missing values in bathroom column are: {df['bathroom'].isnull().sum()}")

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64
Number of missing values in bathroom column are: 0

No Missing values in the bathroom column. We can go ahead and clean it

In [17]:
df["bathroom"] = df["bathroom"].str.split(" ").str.get(0).str.strip().astype(int)
df.sample(3)

,property_name,society,property_type,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,rating
2253,2 BHK Flat in Sohna,hcbs sports ville,flat,0.32,4301.0,744.01,Built Up area: 743.99 (69.12 sq.m.),2,2,1 Balcony,NaN,"Sohna, Gurgaon, Haryana",3rd of 13 Floors,NaN,1 to 5 Year Old,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4 out of 5', 'Construction4 out of..."
1905,2 BHK Flat in Sector 23A Gurgaon,ashiana apartment,flat,0.16,2051.0,780.11,Super Built up area 780(72.46 sq.m.),2,2,2 Balconies,NaN,"Sector 23A Gurgaon, Gurgaon, Haryana",1st of 4 Floors,NaN,5 to 10 Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'P...",[],NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
2320,4 BHK Flat in Valley View Estate,valley view estate,flat,1.50,8278.0,1812.03,Carpet area: 1812 (168.34 sq.m.),4,4,3+ Balconies,"Study Room,Servant Room,Others","Valley View Estate, Gurgaon, Haryana",9th of 15 Floors,North,10+ Year Old,"['HANUMAN MANDIR', 'SHIV MANDIR BALIYAWAS', 'I...","['7 Fan', '1 Exhaust Fan', '20 Light', 'No AC'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [18]:
# CLEANING THE BALCONY COLUMN
print(f"{df['balcony'].value_counts()}")
print(f"Number of missing values in balcony column are: {df['balcony'].isnull().sum()}")

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64
Number of missing values in balcony column are: 0

No Missing values in the bathroom column. We can go ahead and clean it. We are not converting this column as interger because we have a category as 3+

In [19]:
df["balcony"] = df["balcony"].str.split(" ").str.get(0).str.strip()
df.sample(3)

,property_name,society,property_type,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,rating
1532,2 BHK Flat in Sector 85 Gurgaon,ss,flat,1.18,7170.0,1645.75,Super Built up area 1640(152.36 sq.m.)Built Up...,2,2,3,NaN,"Sector 85 Gurgaon, Gurgaon, Haryana",4th of 26 Floors,West,1 to 5 Year Old,"['Sri Radhe Krishna Temple', 'Ekta Hospital', ...","['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
2627,1 BHK Flat in Surat Nagar 1,zara aavaas,flat,0.20,6644.0,301.02,Carpet area: 301 (27.96 sq.m.),1,2,2,NaN,"Surat Nagar 1, Gurgaon, Haryana",3rd of 3 Floors,NaN,0 to 1 Year Old,"['Ardee Mall', 'Northern Peripheral Road', 'Mp...",[],NaN,"['Environment4 out of 5', 'Safety3.5 out of 5'..."
658,3 BHK Flat in Sector 79 Gurgaon,mapsko mount ville,flat,1.25,8389.0,1490.05,Super Built up area 1490(138.43 sq.m.)Built Up...,3,3,3,Study Room,"987, Sector 79 Gurgaon, Gurgaon, Haryana",18th of 30 Floors,South,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...","['3 Wardrobe', '1 Stove', '1 Chimney', '1 Modu...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."

In [20]:
# LETS LOOK INTO THE ADDITIONALROOM COLUMN
print(f"{df['additionalRoom'].value_counts()}")
print(f"Number of missing values in additionalRoom column are: {df['additionalRoom'].isnull().sum()}")

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Study Room,Pooja Room                              8
Servant Room,Study Room                            8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Others                                  6
Others,Servant Room                                6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Servant Room,Others                     6
Study Room,Servant Room,Others                     5
Pooja Room,Store Room,Study Room,Servant Room      4
Pooja Room,Study Room,Store Room                   4
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Study Room,Store Room                 2
Pooja Room,Study Room,Others                       2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Store Room,Pooja Room,Servant Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Pooja Room,Servant Room,Study Room,Store Room      1
Pooja Room,Study Room,Store Room,Servant Room      1
Store Room,Pooja Room                              1
Name: count, dtype: int64
Number of missing values in additionalRoom column are: 1305

It looks like there are multiple categories in this column and also there are 1305 null values. So as of now lets just replace these null values with "not available" and convert everything to lower case. We will deal with the categories later.

In [21]:
df["additionalRoom"].fillna("not available", inplace=True)
df["additionalRoom"] = df["additionalRoom"].str.lower()
df.head(3)

/var/folders/wc/dg5vr0h57jvg48dksgcxz02w0000gn/T/ipykernel_66318/3371871795.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["additionalRoom"].fillna("not available", inplace=True)

,property_name,society,property_type,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,flat,0.45,5000.0,900.00,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...","['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,flat,0.50,7692.0,650.03,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,flat,0.40,6722.0,595.06,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [22]:
# LETS CLEAN THE FLOOR NUM COLUMN. WE WILL EXTRACT THE FLOOR NUMBER. (4TH OF 4 FLOORS - WE ARE INTERESTED IN 4)
df["floorNum"].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
2nd   of 2 Floors           26
1st   of 14 Floors          26
3rd   of 3 Floors           26
3rd   of 14 Floors          24
5th   of 14 Floors          24
8th   of 19 Floors          24
11st   of 14 Floors         23
1st   of 1 Floors           23
9th   of 14 Floors          23
9th   of 9 Floors           23
5th   of 12 Floors          22
2nd   of 3 Floors           22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
10th   of 18 Floors         17
9th   of 13 Floors          17
7th   of 15 Floors          17
12nd   of 12 Floors         17
Ground of 1 Floors          17
7th   of 18 Floors          17
3rd   of 18 Floors          16
5th   of 15 Floors          16
9th   of 15 Floors          15
1st   of 3 Floors           15
2nd   of 12 Floors          15
6th   of 12 Floors          15
6th   of 19 Floors          14
Ground of 4 Floors          13
3rd   of 13 Floors          13
5th   of 5 Floors           13
1st   of 2 Floors           13
7th   of 7 Floors           13
10th   of 26 Floors         13
6th   of 10 Floors          13
6th   of 15 Floors          12
10th   of 10 Floors         12
17th   of 17 Floors         11
4th   of 10 Floors          11
11st   of 18 Floors         11
9th   of 26 Floors          11
15th   of 19 Floors         11
9th   of 24 Floors          11
6th   of 6 Floors           11
16th   of 19 Floors         11
8th   of 8 Floors           11
8th   of 12 Floors          11
4th   of 13 Floors          11
7th   of 26 Floors          10
4th   of 12 Floors          10
7th   of 13 Floors          10
2nd   of 19 Floors          10
7th   of 21 Floors          10
12nd   of 18 Floors         10
6th   of 13 Floors          10
4th   of 15 Floors          10
1st   of 26 Floors          10
3rd   of 9 Floors           10
10th   of 12 Floors         10
3rd   of 5 Floors           10
14th   of 15 Floors          9
14th   of 19 Floors          9
12nd   of 17 Floors          9
5th   of 18 Floors           9
3rd   of 12 Floors           9
18th   of 19 Floors          9
8th   of 15 Floors           9
6th   of 16 Floors           9
15th   of 29 Floors          9
8th   of 22 Floors           9
9th   of 20 Floors           9
7th   of 17 Floors           9
13rd   of 14 Floors          9
7th   of 12 Floors           9
6th   of 26 Floors           9
12nd   of 19 Floors          8
10th   of 17 Floors          8
5th   of 9 Floors            8
3rd   of 15 Floors           8
2nd   of 8 Floors            8
9th   of 18 Floors           8
8th   of 24 Floors           8
10th   of 13 Floors          8
8th   of 26 Floors           8
1st   of 19 Floors           8
2nd   of 15 Floors           8
4th   of 26 Floors           8
12nd   of 26 Floors          8
3rd   of 19 Floors           8
8th   of 13 Floors           8
12nd   of 24 Floors          8
9th   of 12 Floors           8
5th   of 13 Floors           8
2nd   of 5 Floors            8
14th   of 24 Floors          8
4th   of 19 Floors           7
9th   of 19 Floors           7
16th   of 16 Floors          7
5th   of 29 Floors           7
11st   of 24 Floors          7
11st   of 11 Floors          7
2nd   of 13 Floors           7
7th   of 19 Floors           7
2nd   of 17 Floors           7
12nd   of 13 Floors          7
11st   of 26 Floors          7
1st   of 13 Floors           7
11st   of 13 Floors          7
8th   of 21 Floors           7
10th   of 21 Floors          7
8th   of 10 Floors           7
13rd   of 13 Floors          7
2nd   of 10 Floors           7
5th   of 20 Floors           7
12nd   of 15 Floors          7
11st   of 12 Floors          6
Ground of 16 Floors          6
5th   of 22 Floors           6
1st   of 5 Floors            6
1st   of 10 Floors           6
2nd   of 20 Floors           6
14th   of 27 Floors          6
16th   of 18 Floors          6
12nd   of 22 Floors          6
11st   of 19 Floors          6
17th   of 19 Floors          6
10th   of 29 Floors          6
10th   of 20 Floors          6
6th   of 9 Floors            6
19th   of 19 Floors          6
Ground of 3 Floors           6
3rd   of 25 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
4th   of 18 Floors           6
15th   of 15 Floors          6
5th   of 25 Floors           6
5th   of 10 Floors           6
10th   of 15 Floors          6
7th   of 20 Floors           6
8th   of 30 Floors           5
11st   of 16 Floors          5
7th   of 8 Floors            5
4th   of 9 Floors            5
9th   of 11 Floors           5
7th   of 27 Floors           5
9th   of 30 Floors           5
8th   of 9 Floors            5
9th   of 22 Floors           5
15th   of 28 Floors          5
4th   of 27 Floors           5
6th   of 17 Floors           5
3rd   of 20 Floors           5
15th   of 18 Floors          5
18th   of 29 Floors          5
10th   of 25 Floors          5
12nd   of 29 Floors          5
5th   of 8 Floors            5
Ground of 19 Floors          5
4th   of 22 Floors           5
6th   of 20 Floors           5
15th   of 21 Floors          5
Ground of 12 Floors          5
11st   of 25 Floors          5
1st   of 12 Floors           5
10th   of 24 Floors          5
10th   of 27 Floors          5
Ground of 21 Floors          5
6th   of 11 Floors           5
16th   of 26 Floors          5
11st   of 30 Floors          5
1st   of 7 Floors            5
1st   of 15 Floors           5
14th   of 16 Floors          5
5th   of 19 Floors           5
14th   of 29 Floors          5
11st   of 29 Floors          5
12nd   of 21 Floors          5
25th   of 25 Floors          4
17th   of 25 Floors          4
13rd   of 21 Floors          4
13rd   of 19 Floors          4
20th   of 26 Floors          4
7th   of 11 Floors           4
8th   of 16 Floors           4
3rd   of 17 Floors           4
12nd   of 30 Floors          4
5th   of 16 Floors           4
7th   of 24 Floors           4
13rd   of 25 Floors          4
17th   of 26 Floors          4
15th   of 16 Floors          4
8th   of 20 Floors           4
3rd   of 10 Floors           4
2nd   of 11 Floors           4
15th   of 26 Floors          4
3rd   of 22 Floors           4
5th   of 24 Floors           4
5th   of 23 Floors           4
Ground of 13 Floors          4
6th   of 30 Floors           4
17th   of 18 Floors          4
14th   of 26 Floors          4
15th   of 25 Floors          4
2nd   of 9 Floors            4
22nd   of 30 Floors          4
15th   of 23 Floors          4
Ground of 17 Floors          4
17th   of 24 Floors          4
15th   of 32 Floors          4
7th   of 9 Floors            4
3rd   of 11 Floors           4
20th   of 20 Floors          4
23rd   of 26 Floors          4
18th   of 32 Floors          4
14th   of 21 Floors          4
2nd   of 16 Floors           4
7th   of 10 Floors           4
19th   of 40 Floors          4
9th   of 10 Floors           4
12nd   of 16 Floors          4
14th   of 17 Floors          4
4th   of 8 Floors            4
11st   of 17 Floors          4
11st   of 15 Floors          4
14th   of 18 Floors          4
19th   of 24 Floors          4
1st   of 18 Floors           4
11st   of 20 Floors          4
22nd   of 24 Floors          4
3rd   of 26 Floors           3
3rd   of 16 Floors           3
10th   of 16 Floors          3
13rd   of 15 Floors          3
10th   of 28 Floors          3
12nd   of 23 Floors          3
4th   of 20 Floors           3
2nd   of 26 Floors           3
31st   of 32 Floors          3
1st   of 11 Floors           3
8th   of 17 Floors           3
21st   of 24 Floors          3
19th   of 21 Floors          3
17th   of 30 Floors          3
1st   of 35 Floors           3
4th   of 21 Floors           3
27th   of 27 Floors          3
14th   of 32 Floors          3
11st   of 27 Floors          3
10th   of 23 Floors          3
2nd   of 22 Floors           3
24th   of 24 Floors          3
21st   of 22 Floors          3
17th   of 20 Floors          3
4th   of 16 Floors           3
6th   of 29 Floors           3
6th   of 24 Floors           3
8th   of 25 Floors           3
30th   of 32 Floors          3
19th   of 30 Floors          3
4th   of 29 Floors           3
17th   of 29 Floors          3
18th   of 18 Floors          3
6th   of 21 Floors           3
5th   of 17 Floors           3
1st   of 25 Floors           3
5th   of 26 Floors           3
19th   of 29 Floors          3
18th   of 30 Floors          3
23rd   of 23 Floors          3
12nd   of 27 Floors          3
18th   of 26 Floors          3
8th   of 11 Floors           3
6th   of 22 Floors           3
6th   of 23 Floors           3
7th   of 23 Floors           3
15th   of 20 Floors          3
15th   of 40 Floors          3
15th   of 22 Floors          3
Ground of 18 Floors          3
16th   of 20 Floors          3
9th   of 21 Floors           3
3rd   of 8 Floors            3
6th   of 8 Floors            3
15th   of 39 Floors          3
20th   of 28 Floors          3
8th   of 40 Floors           3
Ground of 26 Floors          3
10th   of 30 Floors          3
26th   of 30 Floors          3
5th   of 30 Floors           3
9th   of 16 Floors           3
9th   of 40 Floors           3
11st   of 23 Floors          2
Lower Ground of 4 Floors     2
2nd   of 40 Floors           2
23rd   of 29 Floors          2
21st   of 27 Floors          2
13rd   of 20 Floors          2
9th   of 29 Floors           2
10th   of 40 Floors          2
25th   of 29 Floors          2
7th   of 22 Floors           2
13rd   of 30 Floors          2
4th   of 34 Floors           2
8th   of 23 Floors           2
9th   of 27 Floors           2
19th   of 27 Floors          2
3rd   of 24 Floors           2
27th   of 29 Floors          2
2nd   of 28 Floors           2
40th   of 40 Floors          2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
2nd   of 18 Floors           2
2nd   of 7 Floors            2
2nd   of 25 Floors           2
24th   of 30 Floors          2
2nd   of 6 Floors            2
20th   of 22 Floors          2
22nd   of 25 Floors          2
2nd   of 32 Floors           2
43   of 47 Floors            2
1st   of 30 Floors           2
1st   of 20 Floors           2
15th   of 31 Floors          2
1st   of 8 Floors            2
11st   of 21 Floors          2
23rd   of 34 Floors          2
16th   of 34 Floors          2
18th   of 24 Floors          2
16th   of 30 Floors          2
16th   of 27 Floors          2
7th   of 30 Floors           2
14th   of 20 Floors          2
19th   of 20 Floors          2
16th   of 21 Floors          2
8th   of 34 Floors           2
25th   of 30 Floors          2
16th   of 24 Floors          2
20th   of 23 Floors          2
16th   of 36 Floors          2
9th   of 28 Floors           2
2nd   of 24 Floors           2
1st   of 17 Floors           2
3rd   of 33 Floors           2
8th   of 32 Floors           2
10th   of 32 Floors          2
Ground of 51 Floors          2
39th   of 40 Floors          2
28th   of 30 Floors          2
7th   of 16 Floors           2
13rd   of 40 Floors          2
20th   of 25 Floors          2
9th   of 17 Floors           2
4th   of 5 Floors            2
12nd   of 25 Floors          2
1st   of 24 Floors           2
6th   of 31 Floors           2
7th   of 29 Floors           2
1st   of 22 Floors           2
10th   of 22 Floors          2
5th   of 11 Floors           2
2nd   of 21 Floors           2
17th   of 33 Floors          2
8th   of 28 Floors           2
10th   of 11 Floors          2
Ground of 23 Floors          2
8th   of 29 Floors           2
3rd   of 27 Floors           2
14th   of 28 Floors          2
3rd   of 32 Floors           2
15th   of 17 Floors          2
16th   of 32 Floors          2
3rd   of 29 Floors           2
18th   of 21 Floors          2
15th   of 45 Floors          2
7th   of 36 Floors           2
1st   of 16 Floors           2
4th   of 11 Floors           2
5th   of 35 Floors           1
13rd   of 34 Floors          1
3rd   of 28 Floors           1
12nd   of 40 Floors          1
7th   of 40 Floors           1
13rd   of 26 Floors          1
17th   of 28 Floors          1
18th   of 35 Floors          1
22nd   of 40 Floors          1
14th   of 25 Floors          1
Ground of 2 Floors           1
16th   of 41 Floors          1
13rd   of 22 Floors          1
3rd   of 7 Floors            1
17th   of 31 Floors          1
Ground of 40 Floors          1
Ground of 5 Floors           1
21st   of 23 Floors          1
Ground of 22 Floors          1
10th   of 33 Floors          1
3rd   of 30 Floors           1
3rd   of 31 Floors           1
Lower Ground of 1 Floors     1
19th   of 32 Floors          1
Ground of 6 Floors           1
13rd   of 17 Floors          1
20th   of 24 Floors          1
45   of 47 Floors            1
22nd   of 23 Floors          1
30th   of 34 Floors          1
Ground of 25 Floors          1
16th   of 45 Floors          1
1st   of 6 Floors            1
9th   of 25 Floors           1
13rd   of 47 Floors          1
5th   of 36 Floors           1
34th   of 34 Floors          1
34th   of 42 Floors          1
9th   of 23 Floors           1
29th   of 39 Floors          1
33rd   of 33 Floors          1
27th   of 30 Floors          1
4th   of 6 Floors            1
7th   of 28 Floors           1
8th   of 35 Floors           1
Ground of 29 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
5th   of 6 Floors            1
22nd   of 26 Floors          1
3rd   of 36 Floors           1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
14th   of 41 Floors          1
5th   of 34 Floors           1
24th   of 36 Floors          1
17th   of 22 Floors          1
21st   of 36 Floors          1
23rd   of 24 Floors          1
18th   of 22 Floors          1
Basement of 13 Floors        1
12nd   of 34 Floors          1
17th   of 47 Floors          1
18th   of 20 Floors          1
24th   of 27 Floors          1
21st   of 26 Floors          1
26th   of 47 Floors          1
7th   of 25 Floors           1
Ground of 11 Floors          1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
1st   of 44 Floors           1
24th   of 31 Floors          1
24th   of 51 Floors          1
11st   of 22 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
25th   of 36 Floors          1
21st   of 28 Floors          1
7th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
Ground of 24 Floors          1
35th   of 35 Floors          1
10th   of 39 Floors          1
33rd   of 48 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
32nd   of 55 Floors          1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
20th   of 34 Floors          1
29th   of 31 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
3rd   of 6 Floors            1
20th   of 40 Floors          1
31st   of 40 Floors          1
9th   of 42 Floors           1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
16th   of 25 Floors          1
6th   of 25 Floors           1
3rd   of 40 Floors           1
12nd   of 39 Floors          1
8th   of 31 Floors           1
20th   of 30 Floors          1
18th   of 51 Floors          1
19th   of 22 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
38th   of 40 Floors          1
15th   of 27 Floors          1
18th   of 40 Floors          1
35th   of 51 Floors          1
22nd   of 28 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

There are few columns which are not actual floor numbers. They are Ground and Basement. We will convert them into 0 and -1 respectively.

In [23]:
df["floorNum"] = df["floorNum"].str.split(" ").str.get(0).replace("Ground", "0").str.replace("Basement", "-1").str.replace('Lower', "0").str.extract(r'(\d+)nd')
df.sample(5)

,property_name,society,property_type,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features,rating
494,3 BHK Flat in Sector 74 Gurgaon,m3m skywalk,flat,2.20,10901.0,2018.16,Super Built up area 2018(187.48 sq.m.),3,3,3,study room,"Sector 74 Gurgaon, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Omaxe Gurgaon Mall', 'Omaxe Celebration Mall...","['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '11 L...","['Intercom Facility', 'Lift(s)', 'Park']",NaN
240,2 BHK Flat in Sector 84 Gurgaon,pivotal devaan,flat,0.41,7032.0,583.05,Super Built up area 583(54.16 sq.m.)Built Up a...,2,2,2,not available,"Sector 84 Gurgaon, Gurgaon, Haryana",NaN,East,0 to 1 Year Old,"['Dwarka Expressway', 'RPS International Schoo...","['3 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Environment4 out of 5', 'Safety4 out of 5', ..."
166,4 BHK Flat in Sector 67A Gurgaon,aardhya homesh,flat,1.85,8043.0,2300.14,Carpet area: 2300 (213.68 sq.m.),4,4,No,not available,"Sector 67a, Gurgaon, Haryana, India, Sector 67...",NaN,East,undefined,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2770,3 BHK Flat in Sector 90 Gurgaon,shree vardhman flora,flat,0.95,6333.0,1500.08,Carpet area: 1500 (139.35 sq.m.),3,3,3,servant room,"B3/901, Sector 90 Gurgaon, Gurgaon, Haryana",NaN,South-East,1 to 5 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'In...","['Management4 out of 5', 'Green Area5 out of 5..."
2756,3 BHK Flat in Sector 22 Gurgaon,ambience creacions,flat,3.50,19444.0,1800.04,Carpet area: 1800 (167.23 sq.m.),3,4,3+,servant room,"Sector 22, Sector 22 Gurgaon, Gurgaon, Haryana",NaN,East,Within 6 months,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...","['2 Wardrobe', '6 Fan', '4 Geyser', '1 Microwa...",NaN,"['Safety5 out of 5', 'Lifestyle4 out of 5', 'E..."

In [24]:
# IN THE FACING COLUMN LETS CHECK IF THERE ARE ANY NULL VALUES IF YES THEN LETS JUST REPLACE THEM WITH NA AS OF NOW
print(f"{df['facing'].value_counts()}")
print(f"{df['facing'].isnull().sum()}")

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64
874

In [25]:
df["facing"].fillna("NA", inplace=True)

/var/folders/wc/dg5vr0h57jvg48dksgcxz02w0000gn/T/ipykernel_66318/523242599.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["facing"].fillna("NA", inplace=True)

In [26]:
# FINAL CLEANED DATA
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2997 entries, 0 to 3007
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2997 non-null   object
 1   society          2997 non-null   object
 2   property_type    2997 non-null   object
 3   price            2996 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2997 non-null   object
 7   bedRoom          2997 non-null   int64
 8   bathroom         2997 non-null   int64
 9   balcony          2997 non-null   object
 10  additionalRoom   2997 non-null   object
 11  address          2991 non-null   object
 12  floorNum         434 non-null    object
 13  facing           2997 non-null   object
 14  agePossession    2996 non-null   object
 15  nearbyLocations  2906 non-null   object
 16  furnishDetails   2200 non-null   object
 17  features         2590 non-null   object
 18  rating           2668 non-null   object
dtypes: float64(3), int64(2), object(14)
memory usage: 468.3+ KB

In [27]:
df.shape

(2997, 19)

In [29]:
from pathlib import Path 

curr_dir = Path("/Users/siddhant/housepriceproject/Capstone/notebooks/flats-preprocessing.ipynb")
home_dir = curr_dir.parent.parent.parent
destination_dir = home_dir / 'Capstone' / 'data' / 'processed'

destination_dir.mkdir(parents=True, exist_ok=True)

filename = "cleaned_flats.csv"
filepath = destination_dir / filename

df.to_csv(filepath, index=False)